version: '3.6'

services:
  db:
    image: mariadb:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=db-root-password"
      - "MYSQL_USER=authenticator"
      - "MYSQL_PASSWORD=db-password"
      - "MYSQL_DATABASE=authenticator"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3311:3306

  authenticator:
    image: cghislai/authenticator:latest
    command: '--deploy /run/authenticator-web.war --systemProperties /run/authenticator.properties'
    environment:
      - "DB_DRIVER=mariadb"
      - "DB_SERVER=db"
      - "DB_USER=authenticator"
      - "DB_PASSWORD=db-password"
      - "DB_NAME=authenticator"
      - "JAVA_ARGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9009"
    volumes:
      - '/dev/urandom:/dev/random'
      - '../../authenticator-web/target/authenticator-web.war:/run/authenticator-web.war'
      - './authenticator.properties:/run/authenticator.properties'
      - './keystore.jks:/run/keystore.jks'
      - './cacerts.jks:/run/cacerts.jks'
    ports:
      - 8443:8443
      - 4848:4848
      - 9001:9009

  admin-front:
    image: cghislai/authenticator-admin-front:dev
    environment:
      - "AUTHENTICATOR_URL=https://localhost:8443/authenticator-web"
    ports:
      - 8001:80

volumes:
  db-data: {}
