GET {{adminApiUrl}}/application/8/secretToken
Accept: text/plain
Authorization: Basic YWRtaW46Y2hhbmdlbWU=

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

