PUT {{adminApiUrl}}/user/48/password
Content-Type: text/plain
Authorization: Basic {{adminAuthBase64}}

password1!

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 204, "Response status is not 200");
    });
%}

###

